name: JavaScraft
main: com.lehuen.nukkit.javascraft.JavaScraftPlugin
version: "1.0.0"
api: ["1.0.0"]

load: POSTWORLD
author: nicolas@lehuen.com
description: JavaScript support for Nukkit.
# website: https://github.com/nlehuen/JavaScraft
commands:
  eval0ds:
    description: Evaluate JavaScript expression
    usage: "/eval <JavaScript expression>"
    permission: javascraft.command.eval
permissions:
  javascraft.command.eval:
    description: "Allows the user to evaluate JavaScript expressions"
    default: true